### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by zuixiaosanlang** [hjwdzh/PrimitiveNet#12]
want to test my pointcloud, But i do not know how to prepare data for input.

![image](https://user-images.githubusercontent.com/20105627/195289370-adb8e30a-e9f6-4b8b-b787-051229529ffc.png)

I, FN, B，VC  ??? 
what means this file .txt?
.ply file can get these data??

thanks

**Comment by Tomoki-0526** [comment]
哈哈哈老哥我也想测试下自己的点云，也是不知道这些文件都是啥意思，请问下你现在知道了吗

**Comment by zuixiaosanlang** [comment]
只需准备 v, n , f, vc 三个文件txt数据（分别为顶点、法向、三角面、三角面中心坐标），就可以测试自己的3d模型了；
其他txt文件，其实代码中是没用到的，具体啥意思我也不知道

**Comment by Tomoki-0526** [comment]
@zuixiaosanlang 点云只有顶点信息怎么办呢？是要单独计算出另外三个信息吗

**Comment by zuixiaosanlang** [comment]
@Tomoki-0526 是的，由点云弄个mesh出来，三角面有了，其他都好弄了

**Comment by Tomoki-0526** [comment]
@zuixiaosanlang 好的🙏🏻🙏🏻感谢大佬
