### ISSUE TITLE
Mismatched parameters and an IndexError

### ISSUE THREAD

**Issue by Tomoki-0526** [hjwdzh/PrimitiveNet#13]
There is a problem about mismatched parameters when executing _sh scripts/test_scene.sh_:
![屏幕截图 2022-10-17 113922](https://user-images.githubusercontent.com/73088234/196084254-353f758a-c74d-404e-a062-63f037bc34b3.png)
I tried solving it by the method found on the Internet that let me ignore the weight and bias using the following code: 

> checkpoint.pop("linear_semantics.bias")
    checkpoint.pop("linear_semantics.weight")

But then I encountered another problem raising an IndexError:
![屏幕截图 2022-10-17 114325](https://user-images.githubusercontent.com/73088234/196084662-df078f71-38a1-4e17-ad94-89898cb1f5a4.png)
How can I handle this? Or if there is another way for the mismatched parameters?

**Comment by zuixiaosanlang** [comment]
@Tomoki-0526 哥们，作者上传的checkpoint 与代码配置有点出入，你把config/scene.xml 那个 class由10改为2，就正常了

**Comment by Tomoki-0526** [comment]
@zuixiaosanlang 我焯，老哥厉害，但是后面这个v_files[ii]越界怎么处理呢

**Comment by zuixiaosanlang** [comment]
@Tomoki-0526 路径字符串也要改一下，
'../data/Scene/*%s*_v.txt' 

Scene 改为小写的 scene，下载的数据解压后是小写的

这个作者大牛有点马虎

**Comment by Tomoki-0526** [comment]
@zuixiaosanlang 老哥救命恩人5555555
