### ISSUE TITLE
Prediction when inputs are point clouds

### ISSUE THREAD

**Issue by MulinYu** [hjwdzh/PrimitiveNet#3]
Hello,

Thanks for providing the source code.

I tried to use your code to segment a point cloud. I noticed that your code directly read the edge information from the '.npz' files. In your paper, you said that 'Otherwise we generate k=16 nearest neighbors from each point to form E'. So I think your code has the ability to segment a point cloud without providing 'F' in the input file, right? Can you explain how to do that?

Thanks in advance.
Best.
Mulin

**Comment by hjwdzh** [comment]
The scene data is processed without F. knn utility is in "src/lib/knn/knn.cc".
