### ISSUE TITLE
Wrong pre-trained model?

### ISSUE THREAD

**Issue by MulinYu** [hjwdzh/PrimitiveNet#4]
Hello,

I tried using your provided ABC pre-trained model to test your ABC data. The results are bad, I think that you maybe provide the wrong pre-trained model. 

It's normal that after unzipping the 'abc.pth' file, there is a ' scene.pth' file in the checkpoints folder?

Thanks in advance.
Best.
Mulin

**Comment by MulinYu** [comment]
The output of evaluation is as follow:

0.5 0.00517630176301763
0.55 0.0043819188191881915
0.6000000000000001 0.003664411644116441
0.6500000000000001 0.003254407544075441
0.7000000000000002 0.0029212792127921283
0.7500000000000002 0.0026137761377613778
0.8000000000000003 0.0024600246002460025
0.8500000000000003 0.0022037720377203773
0.9000000000000004 0.0021781467814678147
0.25 0.04440856908569086

**Comment by hjwdzh** [comment]
This is definitely incorrect. Did you find the pretrained model which is named abc-pretrained.pth? If not, probably I did not upload the correct one... Let me know. If not, I will re-upload the model.

**Comment by hjwdzh** [comment]
I just verified and confirmed that my uploaded one is broken... I will upload a new one in 3-5 days. Will let you know when it is ready.

**Comment by MulinYu** [comment]
> I just verified and confirmed that my uploaded one is broken... I will upload a new one in 3-5 days. Will let you know when it is ready.

Thanks a lot.

**Comment by hjwdzh** [comment]
Please view the new link in download.sh.
