### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by CamilleMaurice** [hjwdzh/PrimitiveNet#6]
Hello all,

Does anybony managed to install it on Windows ? It fails at the python setup.py bdist_wheel inside /src/lib/spconv.

I saw that there is a version of spconv in a different repo that can be installed on Windows but I'm not sure how I can deal with that change. https://github.com/traveller59/spconv/

Any help is welcome, if I go further in my troubleshooting I'll post here.

Thank you
CM

**Comment by hjwdzh** [comment]
I actually only made some minor changes to make it compilable on my machine. There should be no functional changes, and I guess the pretrained model can be directly apply to the original version :)

**Comment by CamilleMaurice** [comment]
How great! I'm eager to test this now. Thank you.
