### ISSUE TITLE
Got error when running compile.sh

### ISSUE THREAD

**Issue by Mzzzzzzzzz** [hjwdzh/PrimitiveNet#7]
when running compile i got 
    ERROR: spconv-1.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
my platform is python 3.6 CUDA 10.2  pytorch 1.10.1 and i want to know the version of yours

**Comment by hjwdzh** [comment]
You can modify the compile script to adjust your system. I believe it is fine with python3.6 and cuda 10.2.
